;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	dabbrev-expand
	forward-sentence
	menu-bar-options-save
	menu-set-font
	ruby-end-space
	yaml-electric-bar-and-angle
	))

(setq mc/cmds-to-run-once
      '(
	backward-sentence
	indent-for-tab-command
	yaml-electric-backspace
	))
